version: 2 
jobs:
  build:
    docker:
      - image: gcc:8.1.0
    working_directory: ~/work
    steps:
      - checkout 
      - run: make
      - run: | 
      # tell the OS to remove the file size limit of core dump 
        ulimit -c unlimited 
        ./dump 
      - run:
          command: | 
            mkdir -p /tmp/core_dumps
            cp core.* /tmp/core_dumps
          when: on_fail 
      - store_artifacts:
          path: /tmp/core_dumps
